app:
  name: "HR Pulse API"
  version: "1.0.0"
  description: "API for HR Pulse Employee Directory"
  debug: true

database:
  uri: "mongodb://localhost:27017"
  name: "hr_pulse_db"
  collections:
    employees: "employees"
    users: "users"

security:
  jwt_secret: "your-super-secret-key-change-this-in-production"
  jwt_algorithm: "HS256"
  token_expire_minutes: 60

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "*" 