app:
  name: "HR Pulse API"
  version: "1.0.0"
  description: "API for HR Pulse Employee Directory"
  debug: true

database:
  uri: "mongodb://localhost:27017"
  name: "hr_pulse_db"
  collections:
    employees: "employees"
    users: "users"

server:
  host: "0.0.0.0"
  port: 8000

security:
  secret_key: "your-secret-key-for-development-replace-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "*" 